sudo: required

language: c++

services:
  - docker

before_install:
- uname -a
- docker pull psteinb/sqy-on-trusty
# - docker pull carlad/sinatra 
# - docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
- docker ps -a
# - docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

script:
- docker run psteinb/sqy-on-trusty uname -a