sudo: required

language: c++

services:
  - docker

before_install:
- lsb_release -a
- docker pull psteinb/sqy-on-trusty
- docker ps -a

script:
- pwd #/home/travis/build/sqeazy/sqeazy
- ls -lrth
- docker run psteinb/sqy-on-trusty lsb_release -a
- docker run -v /home/travis/build/sqeazy/sqeazy:/build psteinb/sqy-on-trusty ls /build
- docker run -v /home/travis/build/sqeazy/sqeazy:/build psteinb/sqy-on-trusty gradle clean test
