sudo: required

language: c++

services:
  - docker

before_install:
- lsb_release -a
- docker pull psteinb/sqeazy-testing
- docker ps -a

script:
- pwd #/home/travis/build/sqeazy/sqeazy
- ls -lrth
- docker run psteinb/sqeazy-testing lsb_release -a
- docker run -v /home/travis/build/sqeazy/sqeazy:/build psteinb/sqeazy-testing ls /build
- docker run -v /home/travis/build/sqeazy/sqeazy:/build psteinb/sqeazy-testing gradle clean test
