sudo: required

language: c++

services:
  - docker

before_install:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker pull psteinb/sqy-on-trusty
- docker ps -a
- docker run psteinb/sqy-on-trusty /bin/sh -c "cd /root/sqeazy; gradle test"

script:
  - gradle test