sudo: required

language: c++

services:
  - docker

before_install:
- docker pull psteinb/sqy-on-trusty
- docker ps -a
- docker run psteinb/sqy-on-trusty /bin/sh -c "cd /scratch; gradle test"

script:
  - gradle test