sudo: required

language: c++

services:
  - docker

before_install:
- uname -a
- docker pull psteinb/sqy-on-trusty
- docker ps -a

script:
- pwd
- ls -lrth
- docker run psteinb/sqy-on-trusty uname -a
- docker run psteinb/sqy-on-trusty pwd
- docker run psteinb/sqy-on-trusty ls /
- docker run psteinb/sqy-on-trusty ls /build
- docker run psteinb/sqy-on-trusty gcc --version
- docker run psteinb/sqy-on-trusty gradle --version
#pointing gradle to the right
- docker run psteinb/sqy-on-trusty gradle -b /build/sqeazy/build.gradle test
