sudo: required

language: c++

services:
  - docker

before_install:
- uname -a
- docker pull psteinb/sqy-on-trusty
- docker ps -a

script:
- pwd #/home/travis/build/sqeazy/sqeazy
- ls -lrth
- docker run psteinb/sqy-on-trusty uname -a
- docker run -v /home/travis/build/sqeazy/sqeazy:/sqy ls /sqy
#pointing gradle to the right
#- docker run psteinb/sqy-on-trusty gradle -b /build/sqeazy/build.gradle test
- docker run -v /home/travis/build/sqeazy/sqeazy:/sqy gradle -b /sqy/build.gradle test
