theme: jekyll-theme-slate

title: sqeazy

description: A fast and flexible compression library for 3D volume data (ND potentially planned). The core library is written in C++ with bindings for C, Java (through BridJ), and Python (to be implemented). Binaries are provided for Win (working for the native library), OSX (working for the native library, but not all tests pass), and Linux (works, native library and java bindings).

tagline: A modern modular high-bandwidth compression engine for on-the-microscope data reduction